### ISSUE TITLE
User already exists even after deletion 

### ISSUE THREAD

**Issue by msghaleb** [msghaleb/msg_azure_ad_users#1]
The Module reports the user already exists even after deleting it from the Console

**Comment by msghaleb** [comment]
The Module reports the user already exists even after deletion because while creating you have to pass a ImmutableID. The ImmutableID is only needed if its a federated Domain. If its not federated a unique ID will do. However to check if the user already exist we will have to check on the UPN.

Action Items:
- Before creation check if the UPN already exist.
- Generating a unique ImmutableID for user creation.

**Comment by ahelal** [comment]
I suggest we implement https://msdn.microsoft.com/en-us/Library/Azure/Ad/Graph/api/users-operations#BasicoperationsonusersGetauser

**Comment by msghaleb** [comment]
It works now, setting the ImmutableID to None seems to fix it, it checks then for the UPN. Test it when you have time. We can then close the issue.

**Comment by msghaleb** [comment]
issue solved by setting the ImmutableID to Default=None & Not required.
